export const PHASE6_MODEL_MAP: Record<string, { delegate: string; entityType: string; prefix: string; searchable: string[]; dueField?: string; defaultOrderBy?: Record<string, 'asc' | 'desc'> }> = {
  suppliers: { delegate: 'supplier', entityType: 'Supplier', prefix: 'SUP', searchable: ['legalName', 'description', 'servicesProvided'], dueField: 'nextReviewDate' },
  supplierAssessments: { delegate: 'supplierAssessment', entityType: 'SupplierAssessment', prefix: 'SUA', searchable: ['assessmentType', 'rating', 'status'], dueField: 'nextAssessmentDate' },
  bias: { delegate: 'businessImpactAnalysis', entityType: 'BusinessImpactAnalysis', prefix: 'BIA', searchable: ['title', 'status'], dueField: 'nextReviewDate' },
  bcps: { delegate: 'businessContinuityPlan', entityType: 'BusinessContinuityPlan', prefix: 'BCP', searchable: ['title', 'scope', 'status'], dueField: 'nextTestDate' },
  bcpExercises: { delegate: 'bCPExercise', entityType: 'BCPExercise', prefix: 'BCX', searchable: ['exerciseType', 'status'], dueField: 'plannedAt' },
  auditPrograms: { delegate: 'auditProgram', entityType: 'AuditProgram', prefix: 'AUP', searchable: ['title', 'scope', 'status'] },
  auditPlans: { delegate: 'auditPlan', entityType: 'AuditPlan', prefix: 'AUPL', searchable: ['title', 'scope', 'auditType', 'status'], dueField: 'plannedStart' },
  auditFindings: { delegate: 'auditFinding', entityType: 'AuditFinding', prefix: 'AUF', searchable: ['title', 'description', 'severity', 'status'], dueField: 'dueDate' },
  correctiveActions: { delegate: 'correctiveAction', entityType: 'CorrectiveAction', prefix: 'CAPA', searchable: ['title', 'description', 'sourceType', 'status'], dueField: 'dueDate' },
  trainingCourses: { delegate: 'trainingCourse', entityType: 'TrainingCourse', prefix: 'TRC', searchable: ['title', 'description', 'category', 'status'] },
  trainingAssignments: { delegate: 'trainingAssignment', entityType: 'TrainingAssignment', prefix: 'TRA', searchable: ['status'], dueField: 'dueDate' },
  trainingCompletions: { delegate: 'trainingCompletion', entityType: 'TrainingCompletion', prefix: 'TRCPL', searchable: ['result'], defaultOrderBy: { completedAt: 'desc' } },
  trainingAcknowledgements: { delegate: 'trainingAcknowledgement', entityType: 'TrainingAcknowledgement', prefix: 'TRACK', searchable: ['comment'], defaultOrderBy: { acknowledgedAt: 'desc' } },
  managementReviews: { delegate: 'managementReview', entityType: 'ManagementReview', prefix: 'MREV', searchable: ['title', 'minutes', 'status'], dueField: 'nextReviewDate' },
  managementReviewActions: { delegate: 'managementReviewAction', entityType: 'ManagementReviewAction', prefix: 'MRA', searchable: ['title', 'status'], dueField: 'dueDate' },
  securityObjectives: { delegate: 'securityObjective', entityType: 'SecurityObjective', prefix: 'SOBJ', searchable: ['title', 'description', 'status'] },
  metricDefinitions: { delegate: 'metricDefinition', entityType: 'MetricDefinition', prefix: 'MET', searchable: ['name', 'description', 'metricType', 'status'] },
  metricValues: { delegate: 'metricValue', entityType: 'MetricValue', prefix: 'METV', searchable: ['source', 'comment', 'breachStatus'] },
  workflowDefinitions: { delegate: 'workflowDefinition', entityType: 'WorkflowDefinition', prefix: 'WFD', searchable: ['name', 'entityType', 'status'] },
  workflowInstances: { delegate: 'workflowInstance', entityType: 'WorkflowInstance', prefix: 'WFI', searchable: ['entityType', 'entityId', 'currentState', 'status'], dueField: 'dueDate', defaultOrderBy: { startedAt: 'desc' } },
  workflowTasks: { delegate: 'workflowTask', entityType: 'WorkflowTask', prefix: 'WFT', searchable: ['title', 'taskType', 'status'], dueField: 'dueDate', defaultOrderBy: { createdAt: 'desc' } },
  reportDefinitions: { delegate: 'reportDefinition', entityType: 'ReportDefinition', prefix: 'RPD', searchable: ['name', 'description', 'module', 'status'] },
  reportRuns: { delegate: 'reportRun', entityType: 'ReportRun', prefix: 'RPR', searchable: ['module', 'status'], defaultOrderBy: { startedAt: 'desc' } },
  exportJobs: { delegate: 'exportJob', entityType: 'ExportJob', prefix: 'EXP', searchable: ['entityType', 'format', 'status'], defaultOrderBy: { requestedAt: 'desc' } },
};
