import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import EntityPicker from '../components/EntityPicker';
import { auditWorkflowApi, type AuditDetail, type AuditFinding, type AuditFindingDetail, type AuditProgram, type AuditProgramDetail, type CorrectiveAction } from '../services/api';
import type { EntityPickerResult } from '../services/entityPickerApi';
import { useI18n } from '../context/I18nContext';

type View = { kind: 'programs' } | { kind: 'program'; id: string } | { kind: 'audit'; id: string } | { kind: 'finding'; id: string };
const inputClass = 'w-full rounded border border-gray-300 bg-white px-3 py-2 text-sm dark:border-gray-600 dark:bg-gray-800';
const buttonClass = 'rounded bg-blue-600 px-3 py-2 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50';

function Picker({ label, entityType, multiple = false, value, values, onChange }: { label: string; entityType: 'user' | 'asset' | 'risk' | 'control' | 'requirement' | 'evidence'; multiple?: boolean; value?: EntityPickerResult | null; values?: EntityPickerResult[]; onChange: (value: EntityPickerResult | EntityPickerResult[]) => void }) {
  return <EntityPicker label={label} labelKey="entityPicker.searchPlaceholder" entityType={entityType} multiple={multiple} value={value} values={values} onChange={(item) => onChange(item)} onValuesChange={(items) => onChange(items)} />;
}

export default function AuditWorkspace() {
  const { t } = useI18n();
  const [view, setView] = useState<View>({ kind: 'programs' });
  const [programs, setPrograms] = useState<AuditProgram[]>([]);
  const [programDetail, setProgramDetail] = useState<AuditProgramDetail | null>(null);
  const [auditDetail, setAuditDetail] = useState<AuditDetail | null>(null);
  const [findingDetail, setFindingDetail] = useState<AuditFindingDetail | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [showProgram, setShowProgram] = useState(false);
  const [showAudit, setShowAudit] = useState(false);
  const [showFinding, setShowFinding] = useState(false);
  const [showCapa, setShowCapa] = useState(false);

  const load = useCallback(async () => {
    setError(null);
    try {
      if (view.kind === 'programs') setPrograms((await auditWorkflowApi.listPrograms()).data);
      if (view.kind === 'program') setProgramDetail((await auditWorkflowApi.getProgramDetail(view.id)).data);
      if (view.kind === 'audit') setAuditDetail((await auditWorkflowApi.getAuditDetail(view.id)).data);
      if (view.kind === 'finding') setFindingDetail((await auditWorkflowApi.getFindingDetail(view.id)).data);
    } catch (cause) { setError(cause instanceof Error ? cause.message : t('common.loading')); }
  }, [view, t]);
  useEffect(() => { void load(); }, [load]);
  const run = async (action: () => Promise<unknown>) => { setBusy(true); setError(null); try { await action(); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : t('common.saveError')); } finally { setBusy(false); } };

  return <main className="mx-auto max-w-6xl space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><Link to="/isms-operations" className="text-sm text-blue-600 hover:underline">← {t('ismsOperations.title')}</Link><h1 className="mt-2 text-2xl font-semibold">{t('audit.title')}</h1><p className="text-sm text-gray-500">Program → audit → {t('audit.findings').toLowerCase()} → {t('audit.evidence').toLowerCase()} → CAPA → effectiveness → close/reopen</p></div>{view.kind !== 'programs' && <button className={buttonClass} onClick={() => setView({ kind: 'programs' })}>{t('common.all')}</button>}</header>
    {error && <div role="alert" className="rounded border border-red-300 bg-red-50 p-3 text-sm text-red-800">{error}</div>}

    {view.kind === 'programs' && <section className="space-y-4"><div className="flex justify-between"><h2 className="text-lg font-semibold">{t('audit.auditProgram')}</h2><button className={buttonClass} onClick={() => setShowProgram(true)}>{t('common.create')}</button></div><div className="grid gap-3 md:grid-cols-2">{programs.map((program) => <button key={program.id} onClick={() => setView({ kind: 'program', id: program.id })} className="rounded border p-4 text-left hover:border-blue-500"><strong>{program.displayId} · {program.title}</strong><p className="mt-1 text-sm text-gray-500">{program.year} · {program.status}</p><p className="mt-2 text-sm">{program.scope}</p></button>)}{programs.length === 0 && <p className="text-sm text-gray-500">{t('common.noResults')}</p>}</div>{showProgram && <ProgramForm busy={busy} onCancel={() => setShowProgram(false)} onSave={(data) => run(async () => { await auditWorkflowApi.createProgram(data); setShowProgram(false); })} />}</section>}

    {view.kind === 'program' && programDetail && <section className="space-y-4"><div className="rounded border p-4"><h2 className="text-lg font-semibold">{programDetail.program.displayId} · {programDetail.program.title}</h2><p className="mt-1 text-sm">{programDetail.program.scope}</p></div><div className="flex justify-between"><h3 className="font-semibold">Audits</h3><button className={buttonClass} onClick={() => setShowAudit(true)}>Create audit</button></div><div className="space-y-2">{programDetail.audits.map((audit) => <button key={audit.id} className="w-full rounded border p-3 text-left hover:border-blue-500" onClick={() => setView({ kind: 'audit', id: audit.id })}><strong>{audit.displayId} · {audit.title}</strong><span className="ml-2 text-sm text-gray-500">{audit.status} · {new Date(audit.plannedStart).toLocaleDateString()}</span></button>)}</div>{showAudit && <AuditForm busy={busy} onCancel={() => setShowAudit(false)} onSave={(data) => run(async () => { await auditWorkflowApi.createAudit(programDetail.program.id, data); setShowAudit(false); })} />}</section>}

    {view.kind === 'audit' && auditDetail && <section className="space-y-4"><div className="rounded border p-4"><button className="text-sm text-blue-600" onClick={() => auditDetail.program && setView({ kind: 'program', id: auditDetail.program.id })}>← {auditDetail.program?.title ?? 'Program'}</button><h2 className="mt-2 text-lg font-semibold">{auditDetail.audit.displayId} · {auditDetail.audit.title}</h2><p className="text-sm text-gray-600">{auditDetail.audit.scope}</p></div><div className="flex justify-between"><h3 className="font-semibold">Findings</h3><button className={buttonClass} onClick={() => setShowFinding(true)}>Record finding</button></div><div className="space-y-2">{auditDetail.findings.map((finding) => <FindingCard key={finding.id} finding={finding} onClick={() => setView({ kind: 'finding', id: finding.id })} />)}{auditDetail.findings.length === 0 && <p className="text-sm text-gray-500">No findings recorded.</p>}</div>{showFinding && <FindingForm busy={busy} onCancel={() => setShowFinding(false)} onSave={(data) => run(async () => { await auditWorkflowApi.createFinding(auditDetail.audit.id, data); setShowFinding(false); })} />}</section>}

    {view.kind === 'finding' && findingDetail && <section className="space-y-5"><div className="rounded border p-4"><button className="text-sm text-blue-600" onClick={() => setView({ kind: 'audit', id: findingDetail.audit.id })}>← {findingDetail.audit.title}</button><h2 className="mt-2 text-lg font-semibold">{findingDetail.finding.displayId} · {findingDetail.finding.title}</h2><p className="mt-2 whitespace-pre-wrap text-sm">{findingDetail.finding.description}</p><p className="mt-2 text-sm text-gray-500">{findingDetail.finding.findingType} · {findingDetail.finding.severity} · {findingDetail.finding.status}</p></div><EvidencePanel detail={findingDetail} busy={busy} onRun={run} /><div className="rounded border p-4"><div className="flex justify-between"><h3 className="font-semibold">Corrective action</h3>{!findingDetail.correctiveAction && <button className={buttonClass} onClick={() => setShowCapa(true)}>Generate CAPA</button>}</div>{findingDetail.correctiveAction ? <CapaPanel capa={findingDetail.correctiveAction} busy={busy} onRun={run} /> : <p className="mt-2 text-sm text-gray-500">No CAPA is linked to this finding.</p>}</div>{showCapa && <CapaForm busy={busy} onCancel={() => setShowCapa(false)} onSave={(data) => run(async () => { await auditWorkflowApi.createCapa(findingDetail.finding.id, data); setShowCapa(false); })} />}</section>}
  </main>;
}

function ProgramForm({ onSave, onCancel, busy }: { onSave: (data: Omit<AuditProgram, 'id' | 'displayId'>) => void; onCancel: () => void; busy: boolean }) { const [owner, setOwner] = useState<EntityPickerResult | null>(null); const [title, setTitle] = useState(''); const [scope, setScope] = useState(''); const [year, setYear] = useState(new Date().getFullYear()); return <Form title="Create audit program" onCancel={onCancel} busy={busy} onSubmit={() => owner && onSave({ title, scope, year, ownerId: owner.id, objectives: [], criteria: [], status: 'draft' })}><input required className={inputClass} placeholder="Program title" value={title} onChange={(e) => setTitle(e.target.value)} /><textarea required className={inputClass} placeholder="Program scope" value={scope} onChange={(e) => setScope(e.target.value)} /><input required className={inputClass} type="number" value={year} onChange={(e) => setYear(Number(e.target.value))} /><Picker label="Program owner" entityType="user" value={owner} onChange={(item) => setOwner(item as EntityPickerResult)} /></Form>; }
function AuditForm({ onSave, onCancel, busy }: { onSave: (data: Omit<import('../services/api').AuditPlan, 'id' | 'displayId' | 'programId'>) => void; onCancel: () => void; busy: boolean }) { const [title, setTitle] = useState(''); const [scope, setScope] = useState(''); const [auditors, setAuditors] = useState<EntityPickerResult[]>([]); const [start, setStart] = useState(''); const [end, setEnd] = useState(''); return <Form title="Create audit" onCancel={onCancel} busy={busy} onSubmit={() => onSave({ title, scope, auditType: 'internal', criteria: [], auditorIds: auditors.map((x) => x.id), auditeeIds: [], plannedStart: start, plannedEnd: end, status: 'planned' })}><input required className={inputClass} placeholder="Audit title" value={title} onChange={(e) => setTitle(e.target.value)} /><textarea required className={inputClass} placeholder="Audit scope" value={scope} onChange={(e) => setScope(e.target.value)} /><Picker label="Auditors" entityType="user" multiple values={auditors} onChange={(items) => setAuditors(items as EntityPickerResult[])} /><input required className={inputClass} type="date" value={start} onChange={(e) => setStart(e.target.value)} /><input required className={inputClass} type="date" value={end} onChange={(e) => setEnd(e.target.value)} /></Form>; }
function FindingCard({ finding, onClick }: { finding: AuditFinding; onClick: () => void }) { return <button onClick={onClick} className="w-full rounded border p-3 text-left hover:border-blue-500"><strong>{finding.displayId} · {finding.title}</strong><span className="ml-2 text-sm text-gray-500">{finding.severity} · {finding.status}</span><p className="mt-1 line-clamp-2 text-sm text-gray-600">{finding.description}</p></button>; }
function FindingForm({ onSave, onCancel, busy }: { onSave: (data: Omit<AuditFinding, 'id' | 'displayId' | 'auditPlanId' | 'correctiveActionId'>) => void; onCancel: () => void; busy: boolean }) { const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [owner, setOwner] = useState<EntityPickerResult | null>(null); const [requirements, setRequirements] = useState<EntityPickerResult[]>([]); const [controls, setControls] = useState<EntityPickerResult[]>([]); const [assets, setAssets] = useState<EntityPickerResult[]>([]); const [risks, setRisks] = useState<EntityPickerResult[]>([]); return <Form title="Record audit finding" onCancel={onCancel} busy={busy} onSubmit={() => onSave({ title, description, findingType: 'nonconformity', severity: 'medium', requirementIds: requirements.map((x) => x.id), controlIds: controls.map((x) => x.id), assetIds: assets.map((x) => x.id), riskIds: risks.map((x) => x.id), ownerId: owner?.id, dueDate: null, status: 'open' })}><input required className={inputClass} placeholder="Finding title" value={title} onChange={(e) => setTitle(e.target.value)} /><textarea required className={inputClass} placeholder="Finding description" value={description} onChange={(e) => setDescription(e.target.value)} /><Picker label="Finding owner" entityType="user" value={owner} onChange={(item) => setOwner(item as EntityPickerResult)} /><Picker label="Requirements" entityType="requirement" multiple values={requirements} onChange={(items) => setRequirements(items as EntityPickerResult[])} /><Picker label="Controls" entityType="control" multiple values={controls} onChange={(items) => setControls(items as EntityPickerResult[])} /><Picker label="Assets" entityType="asset" multiple values={assets} onChange={(items) => setAssets(items as EntityPickerResult[])} /><Picker label="Risks" entityType="risk" multiple values={risks} onChange={(items) => setRisks(items as EntityPickerResult[])} /></Form>; }
function EvidencePanel({ detail, onRun, busy }: { detail: AuditFindingDetail; onRun: (action: () => Promise<unknown>) => Promise<void>; busy: boolean }) { const [evidence, setEvidence] = useState<EntityPickerResult | null>(null); return <div className="rounded border p-4"><h3 className="font-semibold">Evidence</h3><div className="mt-3 flex flex-wrap items-end gap-2"><div className="min-w-64 flex-1"><Picker label="Visible evidence" entityType="evidence" value={evidence} onChange={(item) => setEvidence(item as EntityPickerResult)} /></div><button disabled={!evidence || busy} className={buttonClass} onClick={() => evidence && onRun(() => auditWorkflowApi.addEvidence(detail.finding.id, { evidenceId: evidence.id }))}>Link evidence</button></div><ul className="mt-3 space-y-2">{detail.evidenceRelations.map((relation) => <li className="flex items-center justify-between rounded bg-gray-50 p-2 text-sm dark:bg-gray-800" key={relation.id}><span>{relation.evidence?.title ?? 'Evidence is no longer visible'} · {relation.relationType}</span><button disabled={busy} className="text-red-600" onClick={() => onRun(() => auditWorkflowApi.removeEvidence(detail.finding.id, relation.id))}>Remove</button></li>)}</ul></div>; }
function CapaForm({ onSave, onCancel, busy }: { onSave: (data: any) => void; onCancel: () => void; busy: boolean }) { const [owner, setOwner] = useState<EntityPickerResult | null>(null); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [dueDate, setDueDate] = useState(''); return <Form title="Generate corrective action" onCancel={onCancel} busy={busy} onSubmit={() => owner && onSave({ title, description, ownerId: owner.id, dueDate, priority: 'medium', effectivenessCriteria: '' })}><input required className={inputClass} placeholder="CAPA title" value={title} onChange={(e) => setTitle(e.target.value)} /><textarea required className={inputClass} placeholder="Correction and preventive action" value={description} onChange={(e) => setDescription(e.target.value)} /><Picker label="CAPA owner" entityType="user" value={owner} onChange={(item) => setOwner(item as EntityPickerResult)} /><input required className={inputClass} type="date" value={dueDate} onChange={(e) => setDueDate(e.target.value)} /></Form>; }
function CapaPanel({ capa, onRun, busy }: { capa: CorrectiveAction; onRun: (action: () => Promise<unknown>) => Promise<void>; busy: boolean }) { const [review, setReview] = useState(''); const [reopen, setReopen] = useState(''); return <div className="mt-3 space-y-3 text-sm"><p><strong>{capa.displayId} · {capa.title}</strong> — {capa.status}</p><p className="text-gray-600">Due {new Date(capa.dueDate).toLocaleDateString()} · effectiveness: {capa.effectivenessStatus ?? 'not reviewed'}</p>{['open', 'reopened'].includes(capa.status) && <button disabled={busy} className={buttonClass} onClick={() => onRun(() => auditWorkflowApi.updateCapa(capa.id, { status: 'in_progress' }))}>Start progress</button>}{capa.status === 'in_progress' && <button disabled={busy} className={buttonClass} onClick={() => onRun(() => auditWorkflowApi.updateCapa(capa.id, { status: 'completed' }))}>Mark completed</button>}{['completed', 'closed'].includes(capa.status) && <div className="space-y-2"><textarea className={inputClass} value={review} onChange={(e) => setReview(e.target.value)} placeholder="Effectiveness review evidence and result" /><button disabled={busy || !review} className={buttonClass} onClick={() => onRun(() => auditWorkflowApi.reviewEffectiveness(capa.id, { effectivenessStatus: 'effective', effectivenessReview: review }))}>Review effectiveness</button>{capa.status === 'completed' && <button disabled={busy} className="ml-2 rounded bg-gray-700 px-3 py-2 text-white" onClick={() => onRun(() => auditWorkflowApi.closeCapa(capa.id))}>Close CAPA</button>}</div>}{capa.status === 'closed' && <div className="space-y-2"><textarea className={inputClass} value={reopen} onChange={(e) => setReopen(e.target.value)} placeholder="Required justification for reopening" /><button disabled={busy || !reopen} className="rounded bg-orange-600 px-3 py-2 text-white" onClick={() => onRun(() => auditWorkflowApi.reopenCapa(capa.id, reopen))}>Reopen</button></div>}</div>; }
function Form({ title, children, onSubmit, onCancel, busy }: { title: string; children: React.ReactNode; onSubmit: () => void; onCancel: () => void; busy: boolean }) { return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/40 p-4"><form onSubmit={(e) => { e.preventDefault(); onSubmit(); }} className="mx-auto mt-12 max-w-xl space-y-3 rounded-lg bg-white p-5 shadow dark:bg-gray-900"><h2 className="text-lg font-semibold">{title}</h2>{children}<div className="flex justify-end gap-2"><button type="button" className="rounded border px-3 py-2 text-sm" onClick={onCancel}>Cancel</button><button disabled={busy} className={buttonClass}>Save</button></div></form></div>; }
