import { FormEvent, useEffect, useMemo, useState } from 'react';
import EntityPicker from '../components/EntityPicker';
import type { EntityPickerResult } from '../services/entityPickerApi';
import { nis2Api, type Nis2Answer, type Nis2Assessment, type Nis2Questionnaire, type Nis2Registration } from '../services/api';

const card = 'rounded-lg border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-800';
const input = 'mt-1 block w-full rounded border border-gray-300 bg-white px-3 py-2 dark:border-gray-600 dark:bg-gray-700 dark:text-white';

export default function NIS2() {
  const [questionnaires, setQuestionnaires] = useState<Nis2Questionnaire[]>([]); const [assessments, setAssessments] = useState<Nis2Assessment[]>([]); const [registrations, setRegistrations] = useState<Nis2Registration[]>([]);
  const [questionnaireVersion, setQuestionnaireVersion] = useState(''); const [answers, setAnswers] = useState<Record<string, Nis2Answer>>({}); const [organizationUnit, setOrganizationUnit] = useState<EntityPickerResult | null>(null); const [justification, setJustification] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [registrationAssessmentId, setRegistrationAssessmentId] = useState(''); const [entityType, setEntityType] = useState('important_entity'); const [deadline, setDeadline] = useState(''); const [contactPerson, setContactPerson] = useState(''); const [contactDetails, setContactDetails] = useState(''); const [submissionProof, setSubmissionProof] = useState('');
  const [changeRegistrationId, setChangeRegistrationId] = useState(''); const [changeType, setChangeType] = useState('contact_details'); const [changeDescription, setChangeDescription] = useState(''); const [changeValue, setChangeValue] = useState(''); const [changeDeadline, setChangeDeadline] = useState(''); const [changeProof, setChangeProof] = useState('');
  const selectedQuestionnaire = useMemo(() => questionnaires.find((item) => item.version === questionnaireVersion), [questionnaires, questionnaireVersion]); const approved = assessments.filter((item) => item.status === 'approved' && item.result && item.result !== 'not_in_scope');
  const load = async () => { try { const [q, a, r] = await Promise.all([nis2Api.listActiveQuestionnaires(), nis2Api.listAssessments(), nis2Api.listRegistrations()]); setQuestionnaires(q.data); setAssessments(a.data); setRegistrations(r.data); setQuestionnaireVersion((v) => v || q.data[0]?.version || ''); setRegistrationAssessmentId((v) => v || a.data.find((x) => x.status === 'approved' && x.result !== 'not_in_scope')?.id || ''); setChangeRegistrationId((v) => v || r.data[0]?.id || ''); } catch (caught: any) { setError(caught.response?.data?.message || 'Unable to load NIS2 workflow data.'); } };
  useEffect(() => { void load(); }, []); useEffect(() => { setAnswers({}); }, [questionnaireVersion]);
  const run = async (operation: () => Promise<unknown>, success: string) => { setBusy(true); setError(''); try { await operation(); setMessage(success); await load(); } catch (caught: any) { setError(caught.response?.data?.message || 'The operation could not be completed.'); } finally { setBusy(false); } };
  const createAssessment = (event: FormEvent) => { event.preventDefault(); if (!selectedQuestionnaire) return; const missing = selectedQuestionnaire.questions.find((q) => q.required && (answers[q.key] === undefined || answers[q.key] === '')); if (missing) return setError(`Answer required: ${missing.label}`); void run(() => nis2Api.createAssessment({ organizationUnitId: organizationUnit?.id, questionnaireVersion, answers, justification: justification || undefined }), 'Assessment created as draft.'); };
  const createRegistration = (event: FormEvent) => { event.preventDefault(); void run(() => nis2Api.createRegistration({ assessmentId: registrationAssessmentId, entityType, deadline, contactPerson: contactPerson || undefined, contactDetails: contactDetails || undefined, submissionProof: submissionProof || undefined }), 'Registration recorded.'); };
  const createChange = (event: FormEvent) => { event.preventDefault(); void run(() => nis2Api.recordRegistrationChange(changeRegistrationId, { changeType, description: changeDescription, changedData: { value: changeValue }, notificationDeadline: changeDeadline || undefined, submissionProof: changeProof || undefined, submittedAt: changeProof ? new Date().toISOString() : undefined }), 'Registration change recorded.'); };
  return <div className="space-y-6"><header><h1 className="text-2xl font-bold text-gray-900 dark:text-white">NIS2 applicability and registration</h1><p className="mt-1 text-sm text-gray-600">Questionnaire → assessment → submit → approve → registration → changes.</p></header>{message && <p className="rounded bg-green-50 p-3 text-green-800">{message}</p>}{error && <p className="rounded bg-red-50 p-3 text-red-800">{error}</p>}
    <section className={card}><h2 className="text-lg font-semibold">1. Create applicability assessment</h2><form className="mt-4 grid gap-4" onSubmit={createAssessment}><label>Active questionnaire<select className={input} value={questionnaireVersion} onChange={(e) => setQuestionnaireVersion(e.target.value)} required>{questionnaires.map((q) => <option key={q.id} value={q.version}>{q.title} (v{q.version})</option>)}</select></label><EntityPicker label="Organization unit (optional)" labelKey="entityPicker.searchPlaceholder" entityType="organizationUnit" value={organizationUnit} onChange={setOrganizationUnit} />{selectedQuestionnaire?.questions.map((q) => <label key={q.key}>{q.label}{q.required ? ' *' : ''}{q.type === 'boolean' ? <select className={input} value={String(answers[q.key] ?? '')} onChange={(e) => setAnswers({ ...answers, [q.key]: e.target.value === 'true' })} required={q.required}><option value="">Select…</option><option value="true">Yes</option><option value="false">No</option></select> : <input className={input} type={q.type === 'number' ? 'number' : 'text'} value={String(answers[q.key] ?? '')} onChange={(e) => setAnswers({ ...answers, [q.key]: q.type === 'number' ? Number(e.target.value) : e.target.value })} required={q.required} />}</label>)}<label>Justification (optional)<textarea className={input} value={justification} onChange={(e) => setJustification(e.target.value)} /></label><button disabled={busy} className="w-fit rounded bg-blue-600 px-4 py-2 text-white">Create draft assessment</button></form></section>
    <section className={card}><h2 className="text-lg font-semibold">2. Submit and approve</h2><div className="mt-3 space-y-2">{assessments.map((a) => <div key={a.id} className="flex flex-wrap items-center justify-between gap-3 rounded border p-3"><span><strong>{a.result?.replace(/_/g, ' ') || 'Pending'}</strong> · {a.status} · questionnaire v{a.questionnaireVersion}</span>{a.status === 'draft' ? <button disabled={busy} onClick={() => void run(() => nis2Api.submitAssessment(a.id), 'Assessment submitted for approval.')} className="rounded border px-3 py-1">Submit</button> : a.status === 'under_review' ? <button disabled={busy} onClick={() => void run(() => nis2Api.approveAssessment(a.id), 'Assessment approved.')} className="rounded bg-green-600 px-3 py-1 text-white">Approve</button> : null}</div>)}{!assessments.length && <p className="text-sm text-gray-500">No assessments created yet.</p>}</div></section>
    <section className={card}><h2 className="text-lg font-semibold">3. Register approved in-scope entity</h2><form className="mt-4 grid gap-4 md:grid-cols-2" onSubmit={createRegistration}><label>Approved assessment<select className={input} value={registrationAssessmentId} onChange={(e) => setRegistrationAssessmentId(e.target.value)} required><option value="">Select…</option>{approved.map((a) => <option key={a.id} value={a.id}>{a.result?.replace(/_/g, ' ')} · v{a.questionnaireVersion}</option>)}</select></label><label>Entity type<select className={input} value={entityType} onChange={(e) => setEntityType(e.target.value)}><option value="essential_entity">Essential entity</option><option value="important_entity">Important entity</option></select></label><label>Registration deadline *<input className={input} type="date" value={deadline} onChange={(e) => setDeadline(e.target.value)} required /></label><label>Contact person<input className={input} value={contactPerson} onChange={(e) => setContactPerson(e.target.value)} /></label><label>Contact details<input className={input} value={contactDetails} onChange={(e) => setContactDetails(e.target.value)} /></label><label>Submission proof/reference<input className={input} value={submissionProof} onChange={(e) => setSubmissionProof(e.target.value)} /></label><button disabled={busy || !approved.length} className="w-fit rounded bg-blue-600 px-4 py-2 text-white">Create registration</button></form></section>
    <section className={card}><h2 className="text-lg font-semibold">4. Log registration change</h2><form className="mt-4 grid gap-4 md:grid-cols-2" onSubmit={createChange}><label>Registration<select className={input} value={changeRegistrationId} onChange={(e) => setChangeRegistrationId(e.target.value)} required><option value="">Select…</option>{registrations.map((r) => <option key={r.id} value={r.id}>{r.entityType.replace(/_/g, ' ')} · {r.status}</option>)}</select></label><label>Change type<select className={input} value={changeType} onChange={(e) => setChangeType(e.target.value)}><option value="contact_details">Contact details</option><option value="entity_data">Entity data</option><option value="scope">Scope</option><option value="other">Other</option></select></label><label className="md:col-span-2">Description *<textarea className={input} value={changeDescription} onChange={(e) => setChangeDescription(e.target.value)} required /></label><label>New value / summary *<input className={input} value={changeValue} onChange={(e) => setChangeValue(e.target.value)} required /></label><label>Notification deadline<input className={input} type="date" value={changeDeadline} onChange={(e) => setChangeDeadline(e.target.value)} /></label><label>Submission proof/reference<input className={input} value={changeProof} onChange={(e) => setChangeProof(e.target.value)} /></label><button disabled={busy || !registrations.length} className="w-fit rounded bg-blue-600 px-4 py-2 text-white">Record change</button></form><details className="mt-5 border-t pt-4"><summary className="cursor-pointer font-medium">Catalog administration</summary><p className="mt-2 text-sm text-gray-600">Authorized control administrators can initialize the NIS2 measures catalogue. This explicit catalog action is not part of incident management.</p><button disabled={busy} onClick={() => void run(() => nis2Api.ensureMeasuresCatalogue(), 'NIS2 measures catalogue ensured.')} className="mt-2 rounded border px-3 py-1">Ensure NIS2 measures catalogue</button></details></section>
  </div>;
}
